<?php
/**
 * Provides main functionality of the module
 */

/**
 * Implements hook_theme().
 */
function mbc_app_theme($existing, $type, $theme, $path) {
  $logged_in = \Drupal::currentUser()->isAuthenticated();
  return array(
    'page__mbc_app' => array(
      'title' => 'gridstack',
      'template' => 'page--mbc-app',
      'variables' => array(
        'logged_in' => $logged_in,
      ),
      'base hook' => 'page',
    ),
  );
}

/**
 * Implements hook_js_alter().
 */
function mbc_app_js_alter(&$javascript, \Drupal\Core\Asset\AttachedAssetsInterface $assets) {
  $current_path = \Drupal::service('path.current')->getPath();
  if ($current_path === '/mbc-app') {
    unset($javascript['core/assets/vendor/jquery/jquery.min.js']);
    unset($javascript['core/assets/vendor/jquery.ui/ui/core-min.js']);
    unset($javascript['core/assets/vendor/jquery.ui/ui/draggable-min.js']);
    unset($javascript['core/assets/vendor/jquery.ui/ui/resizable-min.js']);
    unset($javascript['core/assets/vendor/jquery.ui/ui/widget-min.js']);
    unset($javascript['core/assets/vendor/jquery.ui/ui/button-min.js']);
    unset($javascript['core/assets/vendor/jquery.ui/ui/mouse-min.js']);
    unset($javascript['core/assets/vendor/jquery.ui/ui/dialog-min.js']);
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function mbc_app_preprocess_page(&$variables) {
  global $base_url;
  $current_path = \Drupal::service('path.current')->getPath();
  $module_handler = \Drupal::service('module_handler');
  $module_path = $module_handler->getModule('mbc_app')->getPath();
  if ($current_path === '/mbc-app') {
    $variables['#attached']['drupalSettings']['csrf'] = \Drupal::csrfToken()->get('rest');
    $variables['#attached']['drupalSettings']['baseUrl'] = $base_url;
    $variables['#attached']['drupalSettings']['modulePath'] = $module_path;
  }
}