<?php
/**
 * Provides main functionality of the module
 */

/**
 * Implements hook_theme().
 */
function mbc_app_theme($existing, $type, $theme, $path) {
  return array(
    'mbc_app_view' => array(
      'template' => 'view',
      'variables' => array('title' => NULL),
    ),
  );
}

/**
 * Implements hook_js_alter().
 */
function mbc_app_js_alter(&$javascript, \Drupal\Core\Asset\AttachedAssetsInterface $assets) {
  $current_path = \Drupal::service('path.current')->getPath();
  if ($current_path === '/mbc_app') {
    unset($javascript['core/assets/vendor/jquery/jquery.min.js']);
    unset($javascript['core/assets/vendor/jquery.ui/ui/core-min.js']);
    unset($javascript['core/assets/vendor/jquery.ui/ui/draggable-min.js']);
    unset($javascript['core/assets/vendor/jquery.ui/ui/resizable-min.js']);
    unset($javascript['core/assets/vendor/jquery.ui/ui/widget-min.js']);
    unset($javascript['core/assets/vendor/jquery.ui/ui/button-min.js']);
    unset($javascript['core/assets/vendor/jquery.ui/ui/mouse-min.js']);
    unset($javascript['core/assets/vendor/jquery.ui/ui/dialog-min.js']);
  }
}